### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by Tinoxy** [OlympicCode/vHackOSBot-Java#15]
15:47:39 INFO [vHackOSBot-Config] Saved config in 2ms.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at net.olympiccode.vhackos.api.utils.Encryption.md5Hash(Encryption.java:15)
        at net.olympiccode.vhackos.api.requests.Route.compile(Route.java:59)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.verifyDetails(vHackOSAPIImpl.java:104)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.login(vHackOSAPIImpl.java:79)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildAsync(vHackOSAPIBuilder.java:80)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildBlocking(vHackOSAPIBuilder.java:92)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.run(vHackOSBot.java:107)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.main(vHackOSBot.java:51)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more
15:47:44 INFO [vHackOSBot] Shutting down...
15:47:44 INFO [vHackOSBot-Config] Saving config...
15:47:44 INFO [vHackOSBot-Config] Saved config in 1ms.
15:47:44 INFO [vHackOSBot-ConfigAdv] Saving advanced config...
15:47:44 INFO [vHackOSBot-ConfigAdv] Saved advanced config in 1ms.

**Comment by itsfolf** [comment]
Duplicate of #1
Java 9 is currently not working with the bot, for now you will need to add the required module using the command `java -jar --add-modules java.xml.bind vHackOSBot.jar`

**Comment by Tinoxy** [comment]
now it works thanks ;)
