### ISSUE TITLE
Whats the cause of this error?

### ISSUE THREAD

**Issue by ghost** [OlympicCode/vHackOSBot-Java#19]
java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:230)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.j
ava:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at net.olympiccode.vhackos.api.requests.Requester.getResponse(Requester.java:65)
        at net.olympiccode.vhackos.api.requests.Route$CompiledRoute.getResponse(Route.java:166)
        at net.olympiccode.vhackos.api.entities.impl.TaskManagerImpl.reloadTasks(TaskManagerImpl.jav
a:35)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.lambda$setup$2(vHackOSAPIImpl.ja
va:132)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown S
ource)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket Closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.InputRecord.readFully(Unknown Source)
        at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        ... 30 more
13:41:08 ERROR [NetworkingService] Failed to withdraw from 54.165.202.169.

**Comment by itsfolf** [comment]
Are you running multiple bots on the same machine or network?

**Comment by raspher** [comment]
I think it's not the problem @checkium .

This guy (54.165.202.169) can have account balance = 0$ so it is saying bot cannot withdraw, cos you too cannot do that! Another option is if you have 100% account balance (999.999.999$), then is too saying the same. It cannot, cos it cannot, you too cannot :-)

**Comment by itsfolf** [comment]
No, problems like that wouldn't cause that error, that has something to do with either your internet connection or the server's.

**Comment by raspher** [comment]
[cons2.log](https://github.com/OlympicCode/vHackOSBot-Java/files/1872553/cons2.log)
[cons1.log](https://github.com/OlympicCode/vHackOSBot-Java/files/1872554/cons1.log)

from the same machine...

```
$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by itsfolf** [comment]
Gonna ask again, are you running multiple bots on the same machine or network (IP)?

**Comment by itsfolf** [comment]
If so, that is the problem, if you want to run multiple bots you need a different IP, otherwise, the server will block the requests due to their speed, there might be a workaround on the next version due to the customizable request wait times.
