### ISSUE TITLE
vHackOSAPI (api.vhack.cc) error code 500

### ISSUE THREAD

**Issue by raspher** [OlympicCode/vHackOSBot-Java#23]
```
00:45:41 INFO [vHackOSAPI] Loading subsystems...
java.lang.RuntimeException: Failed to get response from vHackOS 500 {https://api.vhack.cc/mobile/15/tasks.php?user=eyJ1aWQiOiI1MTYyNyIsImFjY2Vzc3Rva2VuIjoiMTg3YmY4YWNjNjRlM2Q3MGUzZGM0NjlkMzFkOWRmOGYiLCJsYW5nIjoiZW4ifQ&pass=403d4deab0da26f77d9ae44133422313}
	at net.olympiccode.vhackos.api.requests.Requester.getResponse(Requester.java:73)
	at net.olympiccode.vhackos.api.requests.Route$CompiledRoute.getResponse(Route.java:166)
	at net.olympiccode.vhackos.api.entities.impl.TaskManagerImpl.reloadTasks(TaskManagerImpl.java:35)
	at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.setup(vHackOSAPIImpl.java:129)
	at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.verifyDetails(vHackOSAPIImpl.java:111)
	at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.login(vHackOSAPIImpl.java:79)
	at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildAsync(vHackOSAPIBuilder.java:80)
	at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildBlocking(vHackOSAPIBuilder.java:92)
	at net.olympiccode.vhackos.bot.core.vHackOSBot.run(vHackOSBot.java:107)
	at net.olympiccode.vhackos.bot.core.vHackOSBot.main(vHackOSBot.java:51)
00:45:42 INFO [vHackOSBot] Shutting down...
```

it can be temporary, but the bot is now dead. can we go without unneeded dependency on api.vhack.cc?

**Comment by itsfolf** [comment]
I'll update the bot in the next few minutes

**Comment by raspher** [comment]
Still the same result ...

**Comment by itsfolf** [comment]
even with the bot updated?

**Comment by raspher** [comment]
yup, it'st he link itself problem, maybe just for my ip, idk, i can login from phone. can you check this? [link](https://api.vhack.cc/mobile/15/tasks.php?user=eyJ1aWQiOiI1MTYyNyIsImFjY2Vzc3Rva2VuIjoiZmI5Mzk0MmViY2IyMTBhYTM0MzI3ZWViODE4MWU3YmYiLCJsYW5nIjoiZW4ifQ&pass=4aa85c3209e18a6d6d9fffd68a8b8533)

**Comment by raspher** [comment]
ok, it probably was their bad, now it's working fine, but after update the issue was the same. not it's running.

offtopic: can you do something with cpu usage?

**Comment by itsfolf** [comment]
The CPU usage has been a problem for a while and I haven't figured out the cause yet

**Comment by Ashton-Pi** [comment]
really? I have a raspberry pi 3, basically a credit card size potato, and I get 30-50% running 2 bots, a VNC server, and 7 open tabs with bots running on those, and i can STILL code on the thing. cpu has not been very bad for me. might very by machine tho
