### ISSUE TITLE
Error and then stuck

### ISSUE THREAD

**Issue by Ant-iv** [OlympicCode/vHackOSBot-Java#24]
21:40:05 INFO [MainService] Setting up MainSerice...
java.lang.NullPointerException
        at net.olympiccode.vhackos.bot.core.updating.UpdateService.runService(Up
dateService.java:123)
        at net.olympiccode.vhackos.bot.core.updating.UpdateService.lambda$setup$
0(UpdateService.java:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
21:40:08 WARN [UpdateService] The update service has been shutdown due to an err
or.
21:40:09 INFO [ServerService] Opened 1 server packages, got 4 server, 0 av, 0 fw
 and 0 boosters.
21:40:09 INFO [ServerService] Upgrading server's firewall node 1...
21:40:09 INFO [ServerService] Upgrading server's antivirus node 1...
21:40:16 INFO [MiscService] Collected and restarted miner

**Comment by itsfolf** [comment]
I'll investigate it tomorrow, for now, try restarting or waiting for the maintenance service to restart the update service.

**Comment by Ant-iv** [comment]
Thanks.
