### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zaniyahh** [OlympicCode/vHackOSBot-Java#25]
16:13:57 INFO [vHackOSAPI] Loading subsystems...
java.lang.RuntimeException: Failed to get response from vHackOS 500 {https://api.vhack.cc/mobile/15/tasks.php?user=eyJ1aWQiOiI0ODA5MiIsImFjY2Vzc3Rv
uIjoiMzczY2YyN2M2MTViNTZiOWJlZTk0MjM4ZWViZTA1NzMiLCJsYW5nIjoiZW4ifQ&pass=8c75ac3911d6bb1e326776dcbc90e8dc}
        at net.olympiccode.vhackos.api.requests.Requester.getResponse(Requester.java:96)
        at net.olympiccode.vhackos.api.requests.Route$CompiledRoute.getResponse(Route.java:172)
        at net.olympiccode.vhackos.api.entities.impl.TaskManagerImpl.reloadTasks(TaskManagerImpl.java:35)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.setup(vHackOSAPIImpl.java:133)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.verifyDetails(vHackOSAPIImpl.java:115)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.verifyPreLogin(vHackOSAPIImpl.java:103)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.login(vHackOSAPIImpl.java:86)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildAsync(vHackOSAPIBuilder.java:94)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildBlocking(vHackOSAPIBuilder.java:104)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.run(vHackOSBot.java:105)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.main(vHackOSBot.java:51)
16:14:00 INFO [vHackOSBot] Shutting down...
16:14:00 INFO [vHackOSBot-Config] Saving config...
16:14:00 INFO [vHackOSBot-Config] Saved config in 2ms.
16:14:00 INFO [vHackOSBot-ConfigAdv] Saving advanced config...
16:14:00 INFO [vHackOSBot-ConfigAdv] Saved advanced config in 1ms.

C:\Users\asdasd\Downloads\vHackOSBot>PAUSE
Press any key to continue . . .

**Comment by itsfolf** [comment]
Try restarting the bot

**Comment by Zaniyahh** [comment]
i tried a couple of times.. i will try to restart my modem.

**Comment by Zaniyahh** [comment]
Oh. it's working now. i restart it again.
