### ISSUE TITLE
Failed to get response from vHackOS 404 

### ISSUE THREAD

**Issue by olokos** [OlympicCode/vHackOSBot-Java#36]
java.lang.RuntimeException: Failed to get response from vHackOS 404 {https://api.vhack.cc/mobile/16/store.php?user=[IREMOVEDIT]&pass=[IREMOVEDIT]}
        at net.olympiccode.vhackos.api.requests.Requester.getResponse(Requester.java:96)
        at net.olympiccode.vhackos.api.entities.impl.AppManagerImpl.getApps(AppManagerImpl.java:24)
        at net.olympiccode.vhackos.api.entities.impl.AppManagerImpl.getApp(AppManagerImpl.java:43)
        at net.olympiccode.vhackos.bot.core.misc.MiscService.runService(MiscService.java:81)
        at net.olympiccode.vhackos.bot.core.misc.MiscService.lambda$setup$1(MiscService.java:38)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
01:38:32 WARN [MiscService] The misc service has been shutdown due to an error.
01:38:32 ERROR [NetworkingService] Failed to withdraw from [IREMOVEDIT].
01:38:32 INFO [NetworkingService] Removing bruteforce from [IREMOVEDIT].
01:38:32 WARN [io.sentry.connection.AbstractConnection.lockdown] Initiated a temporary lockdown because of exception: Too many requests to Sentry: https://docs.sentry.io/learn/quotas/
01:38:33 INFO [UpdateService] Boosted the update.

I'm having this popup on random, everything else seems to work good apart from missions.

**Comment by itsfolf** [comment]
Ignore
