### ISSUE TITLE
Finish With Netcoins bug

### ISSUE THREAD

**Issue by siiiik** [OlympicCode/vHackOSBot-Java#4]
When `update.finishWithNetcoin: true` , `update.list` gets ignored ( `update.listmode": "blacklist`)

**Comment by Suburbanno** [comment]
working fine for me, put this error

**Comment by itsfolf** [comment]
I tried and wasn't able to replicate the issue, could you please recheck if it's actually not working?

**Comment by siiiik** [comment]
ok I will check

**Comment by siiiik** [comment]
![1](https://user-images.githubusercontent.com/37489365/37566027-5999a8c2-2aab-11e8-806d-032d3042ecb8.PNG)
![2](https://user-images.githubusercontent.com/37489365/37566029-5c84613a-2aab-11e8-8e3e-0cde11ca41ff.PNG)

**Comment by Babyhamsta** [comment]
I'm having the same issue.. Except my it doesn't matter if its enabled or not. It just errors but, I think it's due to how I put it.

![image](https://user-images.githubusercontent.com/22938086/37737298-4d56b014-2d21-11e8-8442-559eea1ed9d5.png)

**Comment by Babyhamsta** [comment]
I have this issue but, I  think it's because of how I have them listed.

![image](https://user-images.githubusercontent.com/22938086/37737320-5e8d163e-2d21-11e8-99ed-12de635fb465.png)


> java.lang.NullPointerException
        at net.olympiccode.vhackos.bot.core.updating.UpdateService.runService(UpdateService.java:102)
        at net.olympiccode.vhackos.bot.core.updating.UpdateService.lambda$setup$0(UpdateService.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
16:07:05 WARN [UpdateService] The update service has been shutdown due to an error. <

**Comment by Suburbanno** [comment]
"random" ?
higher or lower.

**Comment by itsfolf** [comment]
@Suburbanno nah, there's random too

**Comment by itsfolf** [comment]
@Babyhamsta That error is caused by something else, have you tried restarting?

**Comment by qwertz4321** [comment]
working fine for me but how i can only one firewall update ? , and thank you for the great bot.

**Comment by itsfolf** [comment]
@qwertz4321 Sorry, I can't understand what you mean, did you mean you only want it to update firewall?

**Comment by qwertz4321** [comment]
I want to update only firewall with the bot,what do I have to adjust ?

sry for my english

**Comment by itsfolf** [comment]
@qwertz4321 Set `update.listmode` to `whitelist` and `update.list` to `["Firewall"]`

**Comment by qwertz4321** [comment]
thank you :D

**Comment by Babyhamsta** [comment]
@checkium Yes I have restarted and it keeps doing it..
Only happens when I attempt to add stuff to white/black list.
I think it might be the names I'm using for the apps.
[Can you provide me with all the names? Like if Software Development Kit = SDK or something like that.]

**Comment by itsfolf** [comment]
Fixed at discord, the user had an error in his configuration.

**Comment by qwertz4321** [comment]
@Babyhamsta watch the pic from siiiik updateservice list you mean that ?

**Comment by qwertz4321** [comment]
@checkium i set update.listmode to whitelist and update.list to ["BankingProtection","BruteForce"],
and is not working,


22:34:19 INFO [vHackOSAPI] Login Successful!
22:34:19 INFO [vHackOSAPI] Loading subsystems...
22:34:21 INFO [UpdateService] Setting up UpdateSerice...
22:34:21 INFO [MiscService] Setting up MiscSerice...
22:34:21 INFO [NetworkingService] Setting up NetworkingSerice...
java.lang.NullPointerException
        at net.olympiccode.vhackos.bot.core.updating.UpdateService.runService(UpdateService.java:102)
        at net.olympiccode.vhackos.bot.core.updating.UpdateService.lambda$setup$0(UpdateService.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
22:34:24 WARN [UpdateService] The update service has been shutdown due to an error.

**Comment by qwertz4321** [comment]
works fine ,was my fail in config
