### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Ant-iv** [OlympicCode/vHackOSBot-Java#7]
02:35:09 INFO [vHackOSBot-Config] Creating ConfigFile...
02:35:09 INFO [vHackOSBot-ConfigAdv] Creating ConfigFile...
02:35:09 INFO [UpdateService] Creating UpdateService...
02:35:09 INFO [MiscService] Creating MiscService...
02:35:09 INFO [NetworkingService] Creating NetworkingService...
02:35:10 WARN [io.sentry.DefaultSentryClientFactory] No 'stacktrace.app.packages
' was configured, this option is highly recommended as it affects stacktrace gro
uping and display on Sentry. See documentation: https://docs.sentry.io/clients/j
ava/config/#in-application-stack-frames
02:35:10 WARN [io.sentry.DefaultSentryClientFactory] No 'stacktrace.app.packages
' was configured, this option is highly recommended as it affects stacktrace gro
uping and display on Sentry. See documentation: https://docs.sentry.io/clients/j
ava/config/#in-application-stack-frames
02:35:10 INFO [vHackOSBot-ConfigAdv] Loading advanced config...
02:35:10 INFO [vHackOSBot-ConfigAdv] Loaded advanced config in 539ms.
02:35:10 INFO [vHackOSBot-ConfigAdv] Saving advanced config...
02:35:10 INFO [vHackOSBot-ConfigAdv] Saved advanced config in 66ms.
02:35:10 INFO [vHackOSBot-Config] Loading config...
02:35:10 INFO [vHackOSBot-Config] Loaded config in 86ms.
02:35:10 INFO [vHackOSBot-Config] Saving config...
02:35:10 INFO [vHackOSBot-Config] Saved config in 5ms.
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExce
ption: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source
)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.
java:299)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConn
ection.java:268)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.jav
a:160)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAll
ocation.java:256)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(St
reamAllocation.java:134)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocati
on.java:113)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInter
ceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.ja
va:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.j
ava:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndF
ollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at net.olympiccode.vhackos.api.requests.Requester.getResponse(Requester.
java:65)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.verifyDetail
s(vHackOSAPIImpl.java:106)
        at net.olympiccode.vhackos.api.entities.impl.vHackOSAPIImpl.login(vHackO
SAPIImpl.java:79)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildAsync(vHackOSAPIBu
ilder.java:80)
        at net.olympiccode.vhackos.api.vHackOSAPIBuilder.buildBlocking(vHackOSAP
IBuilder.java:92)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.run(vHackOSBot.java:102)
        at net.olympiccode.vhackos.bot.core.vHackOSBot.main(vHackOSBot.java:46)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed:
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find vali
d certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Sour
ce)
        ... 34 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to
 find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Sourc
e)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown
 Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 40 more
Exception in thread "main" java.lang.NullPointerException
        at net.olympiccode.vhackos.bot.core.vHackOSBot.main(vHackOSBot.java:52)
02:35:12 INFO [vHackOSBot] Shutting down...
02:35:12 INFO [vHackOSBot-Config] Saving config...
02:35:12 INFO [vHackOSBot-Config] Saved config in 4ms.
02:35:12 INFO [vHackOSBot-ConfigAdv] Saving advanced config...
02:35:12 INFO [vHackOSBot-ConfigAdv] Saved advanced config in 4ms.

**Comment by itsfolf** [comment]
Please check your java version

**Comment by itsfolf** [comment]
Closing due to inactivity, please reopen if necessary.
